Check for alias-branch conflict

diff --git a/.github/workflows/deploy-book.yml b/.github/workflows/deploy-book.yml
--- a/.github/workflows/deploy-book.yml
+++ b/.github/workflows/deploy-book.yml
@@ -85,11 +85,22 @@ jobs:
         cut -d: -f1 rules.txt > aliases.txt
         cut -d: -f2 rules.txt > targets.txt
 
+        # Alias named as existing branch
+        if grep -E '\S' aliases.txt; then
+          while IFS= read -r alias; do
+            if grep "^$alias$" branches.txt ; then
+              echo "::error ::Alias \"$alias\" given in \$BRANCH_ALIASES conflicts with existing branch."
+              exit 1
+            fi
+          done < aliases.txt
+        fi
+
         # Non-existent targets
         if grep -E '\S' targets.txt; then
           while IFS= read -r target; do
             if ! grep "^$target$" branches.txt ; then
               echo "::error ::Branch \"$target\" given in \$BRANCH_ALIASES does not exist."
+              exit 1
             fi
           done < targets.txt
         fi
@@ -97,6 +108,7 @@ jobs:
         # Duplicate aliases
         if { sort | uniq -d | grep . -qc; } < aliases.txt; then
           echo "::error ::Duplicate aliases in \$BRANCH_ALIASES: \"$BRANCH_ALIASES\""
+          exit 1
         fi
 
     # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-a-multiline-string
